<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
  </array>
  <key>name</key>
  <string>ShuffleTypedSnippet</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#latexShuffle</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#haddockShuffle</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#lhsShuffle</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#agShuffle</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#haskellShuffle</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#jsShuffle</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>haddockShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[).*( haddock)[\s].*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.normal.shuffle</string>
      <key>name</key>
      <string>source.shuffle.normal</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedHaddockShuffle</string>
        </dict>
      </array>
    </dict>
    <key>nestedHaddockShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\]\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ag.embedded.shuffle</string>
      <key>name</key>
      <string>source.shuffle.embedded.ag</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ShuffleNestedSnippets</string>
        </dict>
      </array>
    </dict>
    <key>lhsShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[).*( lhs2tex)[\s].*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.normal.shuffle</string>
      <key>name</key>
      <string>source.shuffle.normal</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedLhsShuffle</string>
        </dict>
        <dict>
          <key>include</key>
          <string>text.tex.latex.haskell</string>
        </dict>
      </array>
    </dict>
    <key>nestedLhsShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\]\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ag.embedded.shuffle</string>
      <key>name</key>
      <string>source.shuffle.embedded.ag</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ShuffleNestedSnippets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>text.tex.latex.haskell</string>
        </dict>
      </array>
    </dict>
    <key>latexShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[).*( doclatex)[\s].*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.normal.shuffle</string>
      <key>name</key>
      <string>source.shuffle.normal</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedLatexShuffle</string>
        </dict>
        <dict>
          <key>include</key>
          <string>text.tex.latex</string>
        </dict>
      </array>
    </dict>
    <key>nestedLatexShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\]\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ag.embedded.shuffle</string>
      <key>name</key>
      <string>source.shuffle.embedded.ag</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ShuffleNestedSnippets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>text.tex.latex</string>
        </dict>
      </array>
    </dict>
    <key>jsShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[).*( javascript)[\s].*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.normal.shuffle</string>
      <key>name</key>
      <string>source.shuffle.normal</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedJsShuffle</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.js</string>
        </dict>
      </array>
    </dict>
    <key>nestedJsShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\]\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ag.embedded.shuffle</string>
      <key>name</key>
      <string>source.shuffle.embedded.ag</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ShuffleNestedSnippets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.js</string>
        </dict>
      </array>
    </dict>
    <key>haskellShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[).*( hs[\s]).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.normal.shuffle</string>
      <key>name</key>
      <string>source.shuffle.normal</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedHaskellShuffle</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.haskell</string>
        </dict>
      </array>
    </dict>
    <key>nestedHaskellShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\]\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ag.embedded.shuffle</string>
      <key>name</key>
      <string>source.shuffle.embedded.ag</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ShuffleNestedSnippets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.haskell</string>
        </dict>
      </array>
    </dict>
    <key>agShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[).*( ag)[\s].*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.normal.shuffle</string>
      <key>name</key>
      <string>source.shuffle.normal</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedAgShuffle</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.ag</string>
        </dict>
      </array>
    </dict>
    <key>nestedAgShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\]\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ag.embedded.shuffle</string>
      <key>name</key>
      <string>source.shuffle.embedded.ag</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ShuffleNestedSnippets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.ag</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.shuffletypedsnippet</string>
</dict>
</plist>
