<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
  </array>
  <key>name</key>
  <string>ShuffleConditionalNestingSnippet</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#conditionalNesting</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>conditionalNesting</key>
    <dict>
      <key>match</key>
      <string>(\%\%\]\[).*$</string>
      <key>name</key>
      <string>source.shuffle.nested.conditional</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.shuffleconditionalnestingsnippet</string>
</dict>
</plist>
