<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>chs</string>
  </array>
  <key>name</key>
  <string>Shuffle (Haskell)</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>source.shuffletypedsnippet</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#normalShuffle</string>
    </dict>
    <dict>
      <key>include</key>
      <string>source.shufflecommentsnippet</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>normalShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>variable.parameter.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.normal.shuffle</string>
      <key>name</key>
      <string>source.shuffle.normal</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nestedNormalShuffle</string>
        </dict>
        <!-- set haskell as the default source highlighting -->
        <dict>
          <key>include</key>
          <string>source.haskell</string>
        </dict>
      </array>
    </dict>
    <key>nestedNormalShuffle</key>
    <dict>
      <key>begin</key>
      <string>(\%\%\[\[).*$</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\%\%\]\])</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.shuffle</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>source.ag.embedded.shuffle</string>
      <key>name</key>
      <string>source.shuffle.embedded.ag</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>source.ShuffleNestedSnippets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#nestedNormalShuffle</string>
        </dict>
        <!-- set haskell as the default source highlighting -->
        <dict>
          <key>include</key>
          <string>source.haskell</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.shuffle</string>
</dict>
</plist>
